install-tools:
    #!/usr/bin/env bash
    set -eux

    hash rustup || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
    source $HOME/.cargo/env
    rustup install stable

run:
    ../../atlantis-executables/atlantis.darwin  single-run --  cargo run

build-docker:
    docker build . -t atlantis-submission:latest

prepare-submission:
    #!/usr/bin/env bash
    set -eux

    rm -rf build
    mkdir -p build/atlantis-solution
    cp src *.toml *.lock Dockerfile build/atlantis-solution/
    cd build
    tar czf atlantis-solution.tar.gz atlantis-solution

    set +x

    echo
    echo "To submit, add build/atlantis-solution.tar.gz to https://forms.gle/utQt8xdeDg9KY8Rz6"
